### ISSUE TITLE
1.8.0 TODO

### ISSUE THREAD

**Issue by fisharebest** [fisharebest/webtrees#1273]
A list of thing to do / in progress

* [x] Manage media page, create links
* [x] Allow multiple files in media objects
* [x] Edit folder/filenames separately when editing `FILE` fields
* [x] Census-assistant individual and associate search - bring close relatives to the top of the list
* [x] HTML templates for Select2 results - add media, etc.
* [x] Get the select2-bootstrap-theme to work.
* [x] Find a replacement for jQueryUI/draggable for the interactive tree
* [x] Find/replace jQueryUI styling, such as `ui-state-error`
* [x] Gallery/lightbox/viewer
* [x] Icons for non-image media
* [x] Use flysystem/ziparchive instead of pclzip
* [x] Use symfony/http_foundation for requests/responses

**Comment by fisharebest** [comment]
Finally found time to create separate issues and a milestone for these
