### ISSUE TITLE
To do's in Weblate

### ISSUE THREAD

**Issue by tunandras** [fisharebest/webtrees#981]
Though I assume that you marked for yourself the new phrases to translate and to do's in Weblate, just to release them, I list here what I collected so far (probably it's incomplete)--with my temporary translations.

- [x] Configure — Statistics
FamilyTreeStatisticsModule.php

- [x] Configure — Top surnames (Top surnames module)
TopSurnamesModule.php
**"Number of surnames" : "Vezetéknevek száma"**

- [x] Configure — Top given names (Top given names module)
TopGivenNamesModule.php
**"Number of given names" : "Utónevek száma"**

- [x] TopPageViewsModule
**"Number of pages" : "Oldalak száma"**

- [x] GoogleMapsModule.php (in Control panel &gt; Module administration &gt; Google Maps™ &gt; Google Maps™ preferences):

- [x] **"API key" : "API-kulcs"**

- [x] **"Google allows a small number of anonymous map requests per day. If you need more than this, you will need a Google account and an API key." : "A Google napi kisszámú névtelen térképkérelmet enged meg. Ha ennél többet szeretne, Google-fiókra és egy API-kulcsra lesz szüksége."**

- [x] **"Get an API key from Google." : "API-kulcs (megszerzése, beszerzése, szerzése, egyik sem?) a Google-tól."**

- [x] LoginBlockModule.php

- [x] login.php
**"Request a new password" : "Új jelszó kérése"**

- [x] Email subject (it's translated)
**"Lost password request" : "Elveszett a jelszó, újat kérek"**

- [ ] To delete from Weblate phrases of Control panel &gt; Family trees &gt; Manage family trees &gt; Preferences &gt; Layout, Names and 3 items

- [x] Converted button labels to lower-case #966
A lot of full stop at the end of `I18N: A button label` button name identifications and there are some button labels to add--for example "sign in" and "sign out" buttons.

- [ ] Different suggestions in GitHub #968
There is a small chance to create new phrases to translate--while repairing these issues but, who knows?

- [ ] Changes in Weblate after corrections In files--mentioned in #955
**"approve" : "jóváhagy" -&gt; "accept" : "elfogad" (17 pcs)
"undo" : "visszautasít" (2 pcs), "visszavon" (2 Undo from 3 string) -&gt; "reject" : elutasít**

- [ ] Message after deletion #954
Your comment:
> I agree. It would be clearer to say something like "Kiss Béla has been deleted".

**Comment by fisharebest** [comment]
The new translations will be added to translate.webtrees.net soon.
It is better to make one update with all the changes, than to make lots of small updates.

I will do it when I have finished the current changes.

**Comment by tunandras** [comment]
I agree.

It's not urgent, just wanted to hand over for the future (before I loose them).

**Comment by fisharebest** [comment]
All the remaining issues have their own tracker number.
